title: ReadImage
executor:
  name: nodejs
  options:
    entry: index.ts
inputs_def:
  - handle: image
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: sharp
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
icon: ":fa6-solid:file-import:currentColor:"
description: ""
